### ISSUE TITLE
Scoring for Reinvent using Glide

### ISSUE THREAD

**Issue by AlexMortenson** [MolecularAI/maize-contrib#5]
Hello, 

I have recently started using Reinvent4 for a project I'm working on and I've been really enjoying its use. I want to implement docking (from Glide) into my scoring function, but I am still relatively new to Maize and have run into a few issues. 

Attached to this document are configuration files for Reinvent, Reinvent scoring, and Maize, as well the Maize workflow file for Glide. I am wondering what I am currently missing/have wrong in the files provided. All the file paths (unless I am going one directory too far for Glide). 

[config_files.zip](https://github.com/user-attachments/files/18206056/config_files.zip)

Additionally, I have included the error message I received below this message (although it is quite long): 

Let me know if you have any advice or feedback. 

Best, 
Alex 
 

Traceback (most recent call last):
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent_plugins/components/run_program.py", line 26, in run_command
    result = sp.run(command, **args)
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Scr/amm10/miniconda3/envs/maize/bin/maize', '/Scr/amm10/zoliflodacin/reinvent_testing/maize/glide.yml', '--inp', '/Scr/amm10/zoliflodacin/reinvent_testing/staged_eNTRy_docking_test/stage2_test/tmpoes9_v3n/input.json', '--out', '/Scr/amm10/zoliflodacin/reinvent_testing/staged_eNTRy_docking_test/stage2_test/tmpoes9_v3n/output.json', '--parameters', '/Scr/amm10/zoliflodacin/reinvent_testing/staged_eNTRy_docking_test/stage2_test/tmpoes9_v3n/extra.json', '--debug', '--keep', '--log', 'maize.log', '--config', '/Scr/amm10/zoliflodacin/reinvent_testing/maize/test-config.toml']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Scr/amm10/miniconda3/envs/maize/bin/reinvent", line 8, in <module>
    sys.exit(main())
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent/Reinvent.py", line 334, in main
    runner(
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent/runmodes/RL/run_staged_learning.py", line 367, in run_staged_learning
    terminate = optimize(package.terminator)
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent/runmodes/RL/learning.py", line 118, in optimize
    results = self.score()
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent/runmodes/RL/learning.py", line 192, in score
    results = self.scoring_function(
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent/scoring/scorer.py", line 138, in compute_results
    transform_result = compute_transform(
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent/scoring/compute_scores.py", line 101, in compute_transform
    component_results = compute_component_scores(
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent/scoring/compute_scores.py", line 62, in compute_component_scores
    component_results = scoring_function(smilies_non_cached)
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent_plugins/normalize.py", line 22, in wrapper
    return func(self, cleaned_smilies)
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent_plugins/components/comp_maize.py", line 231, in __call__
    _ = run_command(command)
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/reinvent_plugins/components/run_program.py", line 32, in run_command
    raise RuntimeError(
RuntimeError: reinvent_plugins.components.run_program: /Scr/amm10/miniconda3/envs/maize/bin/maize /Scr/amm10/zoliflodacin/reinvent_testing/maize/glide.yml --inp /Scr/amm10/zoliflodacin/reinvent_testing/staged_eNTRy_docking_test/stage2_test/tmpoes9_v3n/input.json --out /Scr/amm10/zoliflodacin/reinvent_testing/staged_eNTRy_docking_test/stage2_test/tmpoes9_v3n/output.json --parameters /Scr/amm10/zoliflodacin/reinvent_testing/staged_eNTRy_docking_test/stage2_test/tmpoes9_v3n/extra.json --debug --keep --log maize.log --config /Scr/amm10/zoliflodacin/reinvent_testing/maize/test-config.toml has failed with exit code 1: stdout=, stderr=Could not find a config file ($XDG_CONFIG_HOME is not set)
/Scr/amm10/github/maize-contrib/maize/steps/mai/molecule/reaction_control.py:1132: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  assert mol.molecules[0].get_tag("mw") is not "0.0"
Could not find a config file ($XDG_CONFIG_HOME is not set)
2024-12-19 22:25:09,718 |  WARNING |             dock | Node of type 'Copy' is a generic and should use explicit parameterization. See the 'Generic Nodes' section in the maize user guide.
2024-12-19 22:25:09,891 |    DEBUG |             dock | Checking if required dependencies are available for 'smiles'...
2024-12-19 22:25:09,976 |    DEBUG |             dock | Checking if required dependencies are available for 'ligprep'...
Traceback (most recent call last):
  File "/Scr/amm10/miniconda3/envs/maize/bin/maize", line 8, in <module>
    sys.exit(main())
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/maize/maize.py", line 89, in main
    graph.check()
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/maize/core/workflow.py", line 892, in check
    super().check_dependencies()
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/maize/core/graph.py", line 398, in check_dependencies
    node.check_dependencies()
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/maize/core/node.py", line 270, in check_dependencies
    run_single_process(self._prepare, name=self.name, executable=self.python.filepath)
  File "/Scr/amm10/miniconda3/envs/maize/lib/python3.10/site-packages/maize/utilities/execution.py", line 346, in run_single_process
    raise queue.get_nowait()
maize.core.node.NodeBuildException: Could not find a valid executable for 'ligprep'. Add an appropriate entry in your global configuration under '[ligprep]', e.g. 'commands.ligprep = "path/to/executable"', 'scripts.ligprep.interpreter = "path/to/interpreter"' and 'scripts.ligprep.location = "path/to/script"' or load an appropriate module with 'modules = ["module_with_ligprep"]'

**Comment by marcobICR** [comment]
Hi, I am using Glide with Maize as well and I didn't have this issue. Did you manage to solve the problem?
